[features]
seeds = false
skip-lint = false

[workspace]
members = ["program"]

[programs.localnet]
crypto_scrabble = "AJVQGSNjciPGhotWNtoRSocWEVWGtFQNqkSVzmgiYMtx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node scripts/patch_idl.mjs && npx ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/anchor/**/*.ts"
